CREDENTIALS:
  USERNAME: ''
  PASSWORD: ''
TAGS: ['london','teamNikon']
TOTAL_LIKES: 3000
TOTAL_FOLLOWS: 4000
LIKES_PER_USER: 5
TOTAL_UNFOLLOWS: 3000
UNWANTED_USER_NAMES_LISTS: ['second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog','free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop','store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos','case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet','sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera','beauty', 'express', 'kredit', 'collection', 'impor', 'preloved','follow', 'follower', 'gain', '.id', '_id', 'bags']
USERS:
  KEEP: ['281122381735','846312106216']
  NEVER_FOLLOW: ['05630825605','1972294360']
