class URL(object):
    root = 'https://www.instagram.com/'
    login = 'https://www.instagram.com/accounts/login/ajax/'
    logout = 'https://www.instagram.com/accounts/logout/'
    tag = 'https://www.instagram.com/explore/tags/'
    photo = 'https://www.instagram.com/p/'
    like = 'https://www.instagram.com/web/likes/%s/like/'
    unlike = 'https://www.instagram.com/web/likes/%s/unlike/'
    comment = 'https://www.instagram.com/web/comments/%s/add/'
    follow = 'https://www.instagram.com/web/friendships/%s/follow/'
    unfollow = 'https://www.instagram.com/web/friendships/%s/unfollow/'
    followed = 'https://www.instagram.com/graphql/query/?query_id=17851374694183129&id=6442226747&first=%s'
    following = 'https://www.instagram.com/graphql/query/?query_id=17874545323001329&id=6442226747&first=%s'
    location = 'https://www.instagram.com/explore/locations/%s/?__a=1'
    user_detail = 'https://i.instagram.com/api/v1/users/%s/info/'
    url_user_detail = 'https://www.instagram.com/%s/'
